<?php
/**
 * OptionQuote
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Model;

use \ArrayAccess;
use \SnapTrade\ObjectSerializer;

/**
 * OptionQuote Class Doc Comment
 *
 * @category Class
 * @description Real-time quote for a single option contract.
 * @package  SnapTrade
 * @implements \ArrayAccess<string, mixed>
 */
class OptionQuote implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OptionQuote';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'symbol' => 'string',
        'bid_price' => 'float',
        'bid_size' => 'int',
        'ask_price' => 'float',
        'ask_size' => 'int',
        'last_price' => 'float',
        'last_size' => 'int',
        'open_interest' => 'int',
        'volume' => 'int',
        'implied_volatility' => 'float',
        'underlying_price' => 'float',
        'timestamp' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'symbol' => null,
        'bid_price' => null,
        'bid_size' => null,
        'ask_price' => null,
        'ask_size' => null,
        'last_price' => null,
        'last_size' => null,
        'open_interest' => null,
        'volume' => null,
        'implied_volatility' => null,
        'underlying_price' => null,
        'timestamp' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'symbol' => false,
		'bid_price' => false,
		'bid_size' => false,
		'ask_price' => false,
		'ask_size' => false,
		'last_price' => false,
		'last_size' => false,
		'open_interest' => false,
		'volume' => false,
		'implied_volatility' => false,
		'underlying_price' => false,
		'timestamp' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'symbol' => 'symbol',
        'bid_price' => 'bid_price',
        'bid_size' => 'bid_size',
        'ask_price' => 'ask_price',
        'ask_size' => 'ask_size',
        'last_price' => 'last_price',
        'last_size' => 'last_size',
        'open_interest' => 'open_interest',
        'volume' => 'volume',
        'implied_volatility' => 'implied_volatility',
        'underlying_price' => 'underlying_price',
        'timestamp' => 'timestamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'symbol' => 'setSymbol',
        'bid_price' => 'setBidPrice',
        'bid_size' => 'setBidSize',
        'ask_price' => 'setAskPrice',
        'ask_size' => 'setAskSize',
        'last_price' => 'setLastPrice',
        'last_size' => 'setLastSize',
        'open_interest' => 'setOpenInterest',
        'volume' => 'setVolume',
        'implied_volatility' => 'setImpliedVolatility',
        'underlying_price' => 'setUnderlyingPrice',
        'timestamp' => 'setTimestamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'symbol' => 'getSymbol',
        'bid_price' => 'getBidPrice',
        'bid_size' => 'getBidSize',
        'ask_price' => 'getAskPrice',
        'ask_size' => 'getAskSize',
        'last_price' => 'getLastPrice',
        'last_size' => 'getLastSize',
        'open_interest' => 'getOpenInterest',
        'volume' => 'getVolume',
        'implied_volatility' => 'getImpliedVolatility',
        'underlying_price' => 'getUnderlyingPrice',
        'timestamp' => 'getTimestamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('symbol', $data ?? [], null);
        $this->setIfExists('bid_price', $data ?? [], null);
        $this->setIfExists('bid_size', $data ?? [], null);
        $this->setIfExists('ask_price', $data ?? [], null);
        $this->setIfExists('ask_size', $data ?? [], null);
        $this->setIfExists('last_price', $data ?? [], null);
        $this->setIfExists('last_size', $data ?? [], null);
        $this->setIfExists('open_interest', $data ?? [], null);
        $this->setIfExists('volume', $data ?? [], null);
        $this->setIfExists('implied_volatility', $data ?? [], null);
        $this->setIfExists('underlying_price', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets symbol
     *
     * @return string|null
     */
    public function getSymbol()
    {
        return $this->container['symbol'];
    }

    /**
     * Sets symbol
     *
     * @param string|null $symbol The OCC-formatted option symbol.
     *
     * @return self
     */
    public function setSymbol($symbol)
    {

        if (is_null($symbol)) {
            throw new \InvalidArgumentException('non-nullable symbol cannot be null');
        }

        $this->container['symbol'] = $symbol;

        return $this;
    }

    /**
     * Gets bid_price
     *
     * @return float|null
     */
    public function getBidPrice()
    {
        return $this->container['bid_price'];
    }

    /**
     * Sets bid_price
     *
     * @param float|null $bid_price The best bid price for the option contract.
     *
     * @return self
     */
    public function setBidPrice($bid_price)
    {

        if (is_null($bid_price)) {
            throw new \InvalidArgumentException('non-nullable bid_price cannot be null');
        }

        $this->container['bid_price'] = $bid_price;

        return $this;
    }

    /**
     * Gets bid_size
     *
     * @return int|null
     */
    public function getBidSize()
    {
        return $this->container['bid_size'];
    }

    /**
     * Sets bid_size
     *
     * @param int|null $bid_size The number of contracts available at the bid price.
     *
     * @return self
     */
    public function setBidSize($bid_size)
    {

        if (is_null($bid_size)) {
            throw new \InvalidArgumentException('non-nullable bid_size cannot be null');
        }

        $this->container['bid_size'] = $bid_size;

        return $this;
    }

    /**
     * Gets ask_price
     *
     * @return float|null
     */
    public function getAskPrice()
    {
        return $this->container['ask_price'];
    }

    /**
     * Sets ask_price
     *
     * @param float|null $ask_price The best ask price for the option contract.
     *
     * @return self
     */
    public function setAskPrice($ask_price)
    {

        if (is_null($ask_price)) {
            throw new \InvalidArgumentException('non-nullable ask_price cannot be null');
        }

        $this->container['ask_price'] = $ask_price;

        return $this;
    }

    /**
     * Gets ask_size
     *
     * @return int|null
     */
    public function getAskSize()
    {
        return $this->container['ask_size'];
    }

    /**
     * Sets ask_size
     *
     * @param int|null $ask_size The number of contracts available at the ask price.
     *
     * @return self
     */
    public function setAskSize($ask_size)
    {

        if (is_null($ask_size)) {
            throw new \InvalidArgumentException('non-nullable ask_size cannot be null');
        }

        $this->container['ask_size'] = $ask_size;

        return $this;
    }

    /**
     * Gets last_price
     *
     * @return float|null
     */
    public function getLastPrice()
    {
        return $this->container['last_price'];
    }

    /**
     * Sets last_price
     *
     * @param float|null $last_price The price of the last trade for the option contract.
     *
     * @return self
     */
    public function setLastPrice($last_price)
    {

        if (is_null($last_price)) {
            throw new \InvalidArgumentException('non-nullable last_price cannot be null');
        }

        $this->container['last_price'] = $last_price;

        return $this;
    }

    /**
     * Gets last_size
     *
     * @return int|null
     */
    public function getLastSize()
    {
        return $this->container['last_size'];
    }

    /**
     * Sets last_size
     *
     * @param int|null $last_size The number of contracts in the last trade.
     *
     * @return self
     */
    public function setLastSize($last_size)
    {

        if (is_null($last_size)) {
            throw new \InvalidArgumentException('non-nullable last_size cannot be null');
        }

        $this->container['last_size'] = $last_size;

        return $this;
    }

    /**
     * Gets open_interest
     *
     * @return int|null
     */
    public function getOpenInterest()
    {
        return $this->container['open_interest'];
    }

    /**
     * Sets open_interest
     *
     * @param int|null $open_interest The total number of outstanding contracts.
     *
     * @return self
     */
    public function setOpenInterest($open_interest)
    {

        if (is_null($open_interest)) {
            throw new \InvalidArgumentException('non-nullable open_interest cannot be null');
        }

        $this->container['open_interest'] = $open_interest;

        return $this;
    }

    /**
     * Gets volume
     *
     * @return int|null
     */
    public function getVolume()
    {
        return $this->container['volume'];
    }

    /**
     * Sets volume
     *
     * @param int|null $volume The total number of contracts traded during the current session.
     *
     * @return self
     */
    public function setVolume($volume)
    {

        if (is_null($volume)) {
            throw new \InvalidArgumentException('non-nullable volume cannot be null');
        }

        $this->container['volume'] = $volume;

        return $this;
    }

    /**
     * Gets implied_volatility
     *
     * @return float|null
     */
    public function getImpliedVolatility()
    {
        return $this->container['implied_volatility'];
    }

    /**
     * Sets implied_volatility
     *
     * @param float|null $implied_volatility The implied volatility of the option contract.
     *
     * @return self
     */
    public function setImpliedVolatility($implied_volatility)
    {

        if (is_null($implied_volatility)) {
            throw new \InvalidArgumentException('non-nullable implied_volatility cannot be null');
        }

        $this->container['implied_volatility'] = $implied_volatility;

        return $this;
    }

    /**
     * Gets underlying_price
     *
     * @return float|null
     */
    public function getUnderlyingPrice()
    {
        return $this->container['underlying_price'];
    }

    /**
     * Sets underlying_price
     *
     * @param float|null $underlying_price The current price of the underlying security.
     *
     * @return self
     */
    public function setUnderlyingPrice($underlying_price)
    {

        if (is_null($underlying_price)) {
            throw new \InvalidArgumentException('non-nullable underlying_price cannot be null');
        }

        $this->container['underlying_price'] = $underlying_price;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime|null $timestamp The timestamp of the quote.
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {

        if (is_null($timestamp)) {
            array_push($this->openAPINullablesSetToNull, 'timestamp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('timestamp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['timestamp'] = $timestamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


