<?php
/**
 * PortfolioGroupSettings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Model;

use \ArrayAccess;
use \SnapTrade\ObjectSerializer;

/**
 * PortfolioGroupSettings Class Doc Comment
 *
 * @category Class
 * @package  SnapTrade
 * @implements \ArrayAccess<string, mixed>
 */
class PortfolioGroupSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PortfolioGroupSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'buy_only' => 'bool',
        'cash_optimizer' => 'bool',
        'notify_frequency' => 'string',
        'drift_threshold' => 'float',
        'preferred_currency' => '\SnapTrade\Model\Currency'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'buy_only' => null,
        'cash_optimizer' => null,
        'notify_frequency' => null,
        'drift_threshold' => null,
        'preferred_currency' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'buy_only' => false,
		'cash_optimizer' => false,
		'notify_frequency' => false,
		'drift_threshold' => false,
		'preferred_currency' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buy_only' => 'buyOnly',
        'cash_optimizer' => 'cash_optimizer',
        'notify_frequency' => 'notifyFrequency',
        'drift_threshold' => 'driftThreshold',
        'preferred_currency' => 'preferred_currency'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buy_only' => 'setBuyOnly',
        'cash_optimizer' => 'setCashOptimizer',
        'notify_frequency' => 'setNotifyFrequency',
        'drift_threshold' => 'setDriftThreshold',
        'preferred_currency' => 'setPreferredCurrency'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buy_only' => 'getBuyOnly',
        'cash_optimizer' => 'getCashOptimizer',
        'notify_frequency' => 'getNotifyFrequency',
        'drift_threshold' => 'getDriftThreshold',
        'preferred_currency' => 'getPreferredCurrency'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('buy_only', $data ?? [], null);
        $this->setIfExists('cash_optimizer', $data ?? [], null);
        $this->setIfExists('notify_frequency', $data ?? [], null);
        $this->setIfExists('drift_threshold', $data ?? [], null);
        $this->setIfExists('preferred_currency', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['drift_threshold']) && ($this->container['drift_threshold'] > 100)) {
            $invalidProperties[] = "invalid value for 'drift_threshold', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['drift_threshold']) && ($this->container['drift_threshold'] < 0)) {
            $invalidProperties[] = "invalid value for 'drift_threshold', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buy_only
     *
     * @return bool|null
     */
    public function getBuyOnly()
    {
        return $this->container['buy_only'];
    }

    /**
     * Sets buy_only
     *
     * @param bool|null $buy_only buy_only
     *
     * @return self
     */
    public function setBuyOnly($buy_only)
    {

        if (is_null($buy_only)) {
            throw new \InvalidArgumentException('non-nullable buy_only cannot be null');
        }

        $this->container['buy_only'] = $buy_only;

        return $this;
    }

    /**
     * Gets cash_optimizer
     *
     * @return bool|null
     */
    public function getCashOptimizer()
    {
        return $this->container['cash_optimizer'];
    }

    /**
     * Sets cash_optimizer
     *
     * @param bool|null $cash_optimizer cash_optimizer
     *
     * @return self
     */
    public function setCashOptimizer($cash_optimizer)
    {

        if (is_null($cash_optimizer)) {
            throw new \InvalidArgumentException('non-nullable cash_optimizer cannot be null');
        }

        $this->container['cash_optimizer'] = $cash_optimizer;

        return $this;
    }

    /**
     * Gets notify_frequency
     *
     * @return string|null
     */
    public function getNotifyFrequency()
    {
        return $this->container['notify_frequency'];
    }

    /**
     * Sets notify_frequency
     *
     * @param string|null $notify_frequency notify_frequency
     *
     * @return self
     */
    public function setNotifyFrequency($notify_frequency)
    {

        if (is_null($notify_frequency)) {
            throw new \InvalidArgumentException('non-nullable notify_frequency cannot be null');
        }

        $this->container['notify_frequency'] = $notify_frequency;

        return $this;
    }

    /**
     * Gets drift_threshold
     *
     * @return float|null
     */
    public function getDriftThreshold()
    {
        return $this->container['drift_threshold'];
    }

    /**
     * Sets drift_threshold
     *
     * @param float|null $drift_threshold drift_threshold
     *
     * @return self
     */
    public function setDriftThreshold($drift_threshold)
    {

        if (!is_null($drift_threshold) && ($drift_threshold > 100)) {
            throw new \InvalidArgumentException('invalid value for $drift_threshold when calling PortfolioGroupSettings., must be smaller than or equal to 100.');
        }
        if (!is_null($drift_threshold) && ($drift_threshold < 0)) {
            throw new \InvalidArgumentException('invalid value for $drift_threshold when calling PortfolioGroupSettings., must be bigger than or equal to 0.');
        }


        if (is_null($drift_threshold)) {
            throw new \InvalidArgumentException('non-nullable drift_threshold cannot be null');
        }

        $this->container['drift_threshold'] = $drift_threshold;

        return $this;
    }

    /**
     * Gets preferred_currency
     *
     * @return \SnapTrade\Model\Currency|null
     */
    public function getPreferredCurrency()
    {
        return $this->container['preferred_currency'];
    }

    /**
     * Sets preferred_currency
     *
     * @param \SnapTrade\Model\Currency|null $preferred_currency preferred_currency
     *
     * @return self
     */
    public function setPreferredCurrency($preferred_currency)
    {

        if (is_null($preferred_currency)) {
            throw new \InvalidArgumentException('non-nullable preferred_currency cannot be null');
        }

        $this->container['preferred_currency'] = $preferred_currency;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


