<?php
/**
 * AccountInformationApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Test\Api;

use \SnapTrade\Configuration;
use \SnapTrade\ApiException;
use \SnapTrade\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class AccountInformationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAllUserHoldings
     *
     * List all accounts for the user, plus balances, positions, and orders for each account..
     *
     */
    public function testGetAllUserHoldings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserAccountBalance
     *
     * List account balances.
     *
     */
    public function testGetUserAccountBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserAccountDetails
     *
     * Get account detail.
     *
     */
    public function testGetUserAccountDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserAccountOrders
     *
     * List account recent orders.
     *
     */
    public function testGetUserAccountOrders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserAccountPositions
     *
     * List account positions.
     *
     */
    public function testGetUserAccountPositions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserAccountRecentOrders
     *
     * List account recent executed orders.
     *
     */
    public function testGetUserAccountRecentOrders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserAccountReturnRates
     *
     * List account rate of returns.
     *
     */
    public function testGetUserAccountReturnRates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserHoldings
     *
     * List account holdings.
     *
     */
    public function testGetUserHoldings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listUserAccounts
     *
     * List accounts.
     *
     */
    public function testListUserAccounts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUserAccount
     *
     * Update details of an investment account.
     *
     */
    public function testUpdateUserAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
