<?php
/**
 * CryptoSpotTradingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Test\Api;

use \SnapTrade\Configuration;
use \SnapTrade\ApiException;
use \SnapTrade\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class CryptoSpotTradingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cryptoSpotCancelOrder
     *
     * Cancel a crypto spot order..
     *
     */
    public function testCryptoSpotCancelOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cryptoSpotPlaceOrder
     *
     * Place a spot order on a crypto exchange.
     *
     */
    public function testCryptoSpotPlaceOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cryptoSpotPreviewOrder
     *
     * Preview a crypto spot order.
     *
     */
    public function testCryptoSpotPreviewOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cryptoSpotQuote
     *
     * Get a cryptocurrency spot market quote.
     *
     */
    public function testCryptoSpotQuote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cryptoSpotSymbols
     *
     * Search crypto spot symbols.
     *
     */
    public function testCryptoSpotSymbols()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
