<?php
/**
 * OptionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Test\Api;

use \SnapTrade\Configuration;
use \SnapTrade\ApiException;
use \SnapTrade\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class OptionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getOptionStrategy
     *
     * Creates an option strategy object that will be used to place an option strategy order.
     *
     */
    public function testGetOptionStrategy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOptionsChain
     *
     * Get the options chain.
     *
     */
    public function testGetOptionsChain()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOptionsStrategyQuote
     *
     * Get latest market data of option strategy.
     *
     */
    public function testGetOptionsStrategyQuote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOptionHoldings
     *
     * Get the options holdings in the account.
     *
     */
    public function testListOptionHoldings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for placeOptionStrategy
     *
     * Place an option strategy order on the brokerage.
     *
     */
    public function testPlaceOptionStrategy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
