<?php
/**
 * TradingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Test\Api;

use \SnapTrade\Configuration;
use \SnapTrade\ApiException;
use \SnapTrade\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class TradingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelUserAccountOrder
     *
     * Cancel open order in account.
     *
     */
    public function testCancelUserAccountOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderImpact
     *
     * Check impact of trades on account..
     *
     */
    public function testGetOrderImpact()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserAccountQuotes
     *
     * Get symbol quotes.
     *
     */
    public function testGetUserAccountQuotes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for placeForceOrder
     *
     * Place a trade with NO validation..
     *
     */
    public function testPlaceForceOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for placeOCOOrder
     *
     * Place a OCO (One Cancels Other) order.
     *
     */
    public function testPlaceOCOOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for placeOrder
     *
     * Place order.
     *
     */
    public function testPlaceOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
